#
# Makefile-paolo
#
# This is the Makefile for the paolo_solve program.
#
# This file was generated by the program VFGEN (Version:2.4.0)
# Generated on 22-Jun-2009 at 23:37
#
# This Makefile is not guaranteed to work in all operating systems.
# You may have to edit this file to meet the conventions of your operating system.
#

all: paolo_solve

paolo_solve: paolo_solve.o paolo_gvf.o
	$(CC) $(LDFLAGS) -o paolo_solve paolo_solve.o paolo_gvf.o -lgsl -lgslcblas -lm

paolo_solve.o: paolo_solve.c paolo_gvf.h
	$(CC) $(CPPFLAGS) -c paolo_solve.c

paolo_gvf.o: paolo_gvf.c paolo_gvf.h
	$(CC) $(CPPFLAGS) -c paolo_gvf.c

clean:
	rm -f paolo_solve paolo_solve.o paolo_gvf.o

