/*
 *  paolo_gvf.h
 *
 *  GSL C prototype file for the functions defined in paolo_gvf.c
 *
 *  This file was generated by the program VFGEN (Version:2.4.0)
 *  Generated on 22-Jun-2009 at 23:37
 */

int paolo_vf(double, const double [], double [], void *);
int paolo_jac(double, const double [], double *, double *, void *);
int paolo_jacp(double, const double [], double *, void *);
