/*
 *  paolo_gvf.c
 *
 *  GSL C file for the vector field named: paolo
 *
 *  This file was generated by the program VFGEN (Version:2.4.0)
 *  Generated on 22-Jun-2009 at 23:37
 */

#include <math.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_odeiv.h>

/*
 *  The vector field.
 */

int paolo_vf(double t, const double y_[], double f_[], void *params)
    {
    double F, M;
    double alpha1, alpha2, gamma1, gamma2, mu_f, mu_m;
    double *p_;

    p_ = (double *) params;

    F          = y_[0];
    M          = y_[1];

    alpha1     = p_[0];
    alpha2     = p_[1];
    gamma1     = p_[2];
    gamma2     = p_[3];
    mu_f       = p_[4];
    mu_m       = p_[5];

    f_[0] = -alpha1*F+M*gamma1-t*mu_f;
    f_[1] =  gamma2*F-mu_m*t-M*alpha2;

    return GSL_SUCCESS;
    }

/*
 *  The Jacobian.
 */

int paolo_jac(double t, const double y_[], double *jac_, double *dfdt_, void *params)
    {
    double F, M;
    double alpha1, alpha2, gamma1, gamma2, mu_f, mu_m;
    double *p_;

    p_ = (double *) params;

    F          = y_[0];
    M          = y_[1];

    alpha1     = p_[0];
    alpha2     = p_[1];
    gamma1     = p_[2];
    gamma2     = p_[3];
    mu_f       = p_[4];
    mu_m       = p_[5];

    gsl_matrix_view dfdy_mat = gsl_matrix_view_array(jac_,2,2);
    gsl_matrix *m_ = &dfdy_mat.matrix;

    gsl_matrix_set(m_, 0, 0, -alpha1);
    gsl_matrix_set(m_, 0, 1, gamma1);
    gsl_matrix_set(m_, 1, 0, gamma2);
    gsl_matrix_set(m_, 1, 1, -alpha2);

    dfdt_[0] = 0.0;
    dfdt_[1] = 0.0;

    return GSL_SUCCESS;
    }

/*
 *  The Jacobian with respect to the parameters.
 */

int paolo_jacp(double t, const double y_[], double *jacp_, void *params)
    {
    double F, M;
    double alpha1, alpha2, gamma1, gamma2, mu_f, mu_m;
    double *p_;

    p_ = (double *) params;

    F          = y_[0];
    M          = y_[1];

    alpha1     = p_[0];
    alpha2     = p_[1];
    gamma1     = p_[2];
    gamma2     = p_[3];
    mu_f       = p_[4];
    mu_m       = p_[5];

    gsl_matrix_view dfdp_mat = gsl_matrix_view_array(jacp_,2,6);
    gsl_matrix *m_ = &dfdp_mat.matrix;

    gsl_matrix_set(m_, 0, 0, -F);
    gsl_matrix_set(m_, 0, 1, 0.0);
    gsl_matrix_set(m_, 0, 2, M);
    gsl_matrix_set(m_, 0, 3, 0.0);
    gsl_matrix_set(m_, 0, 4, -t);
    gsl_matrix_set(m_, 0, 5, 0.0);
    gsl_matrix_set(m_, 1, 0, 0.0);
    gsl_matrix_set(m_, 1, 1, -M);
    gsl_matrix_set(m_, 1, 2, 0.0);
    gsl_matrix_set(m_, 1, 3, F);
    gsl_matrix_set(m_, 1, 4, 0.0);
    gsl_matrix_set(m_, 1, 5, -t);

    return GSL_SUCCESS;
    }
